version: 2
updates:
  # master branch
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "master"
    labels:
      - "dependencies"
      - "javascript"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "html-to-text"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pako"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sodium-native"
        update-types: ["version-update:semver-major"]
      - dependency-name: "rimraf"
        update-types: ["version-update:semver-major"]

  # documentation site (master)
  - package-ecosystem: npm
    directory: "/docs/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update(docs):"
    target-branch: "master"
    labels:
      - "dependencies"
      - "javascript"
      - "scope:docs"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "@mdx-js/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
  
  # actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update(action):"
    target-branch: "master"
    labels:
      - "dependencies"
      - "github_actions"
