commit_message: "Change: update translations in %language%"
append_commit_message: false
pull_request_title: "Change: update translations in %language%"
pull_request_labels:
  - language
files:
  - source: /locales/ja/*.json
    translation: /locales/%locale%/%original_file_name%
