project_id: "569777"
api_token_env: CROWDIN_API_TOKEN
commit_message: "Change: update translations in %language%"
append_commit_message: false
pull_request_title: "Change: update translations
pull_request_labels:
  - language
files:
  - source: /locales/ja/*.json
    translation: /locales/%locale%/%original_file_name%
    type: i18next_json
  - source: /README.md
    translation: /locales/README.%two_letters_code%.md
