name: Build Docker

on:
  push:
    branches:
      - master
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/build-docker.yml"
  release:
    types:
      - published
  schedule:
    - cron: "0 15 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.actor }}/discord-music-bot
          flavor: latest=auto
          tags: |
            type=sha
            type=sha,format=long
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=docker
          cache-to: type=gha,mode=max,scope=docker
          context: .
          file: ./Dockerfile
          
      - name: Upload image as artifact
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: ${{ steps.meta.outputs.tags }}
          retention_days: "7"
